apiVersion: v1
kind: Service
metadata:
  name: "api-svc-${HWI_ENV_K8S_CURRENT_DISTRIBUTION}"
  # namespace: "hwi-ns"

spec:
  ports:
    - port: 80
      # targetPort: 8081
      targetPort: api-${HWI_ENV_K8S_CURRENT_DISTRIBUTION}-srv
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: "api-${HWI_ENV_K8S_CURRENT_DISTRIBUTION}"
