apiVersion: v1
kind: Service
metadata:
  name: "hsv-svc-${HWI_ENV_K8S_CURRENT_DISTRIBUTION}"
  # namespace: "hwi-ns"

spec:
  ports:
    - port: 80
      # targetPort: 8081
      targetPort: hsv-${HWI_ENV_K8S_CURRENT_DISTRIBUTION}-srv
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: "hsv-${HWI_ENV_K8S_CURRENT_DISTRIBUTION}"
